### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by dryganets** [facebookarchive/react-native-custom-components#17]
Shouldn't it be licensed under BSD license as the ReactNative framework?

**Comment by hramos** [comment]
Custom Components are licensed separately. Back when they were located in the React Native repository, the README made note of this, and there was a separate LICENSE-CustomComponents file that covered them. See https://github.com/facebook/react-native/commit/777e80a2b73eb58c0c57598fccf27922692a041f.

Part of the reason these Custom Components were moved to their own repo was to move away from the confusing multi-license situation in the core repo (although we still have a separate license for docs in the core repo).

Closing as this is intended.
