### ISSUE TITLE
Navigator documentation URL is broken

### ISSUE THREAD

**Issue by rclai** [facebookarchive/react-native-custom-components#26]
http://facebook.github.io/react-native/releases/0.43/docs/navigator.html

**Comment by jbarradas** [comment]
You all can use web archive while it's not fixed:
http://web.archive.org/web/20170614042049/http://facebook.github.io/react-native/releases/0.43/docs/navigator.html

**Comment by mileung** [comment]
Thanks @jbarradas 

The deprecated Navigator component is still the easiest to use and most straight forward navigator in React Native right now.

**Comment by jbarradas** [comment]
@MiLeung np mate! ;)

And yes, I agree, although it's being deprecated, and if you're doing your app for the long-term, just do not use it. Otherwise you'll end up wanting to upgrade your React Native version, but you'll need to change all the navigation first.

**Comment by hramos** [comment]
Hey! I help maintain [react-native-website](https://github.com/facebook/react-native-website). For any docs issues, please let us know over there. I'm going to look into why the Navigator component is not present in the archives -- might have been missed when we performed the migration to the new site.

**Comment by hramos** [comment]
I've gone back and manually restored these docs. They should be available shortly at a new URL: https://facebook.github.io/react-native/docs/0.43/navigator.html
