### ISSUE TITLE
react-native undefined is not an obj(_react3.default.proptypes.shape)

### ISSUE THREAD

**Issue by labike** [facebookarchive/react-native-custom-components#27]
![image](https://sfault-image.b0.upaiyun.com/227/270/2272700895-5a3382ff6022a_articlex)
add :
```
import PropTypes from 'prop-types'
```
the error also here?
how to resolve the error?

**Comment by zhengxiaoyao0716** [comment]
I found it already fixed  with this commit, but not published to npm.
https://github.com/facebookarchive/react-native-custom-components/commit/44810a7cd17c759598120e1c058e179813af43b4#diff-f8e91e3c1a22214f1ee22845e04973e8

**Comment by sparameshwar** [comment]
When will this fix be published to npm? We are currently blocked on moving to the latest react version due to this.

**Comment by getreup** [comment]
@sparameshwar if you're desperate, use this for now:

`npm i --save react-native-custom-components@https://github.com/facebookarchive/react-native-custom-components.git`

**Comment by kaixin321** [comment]
> @sparameshwar if you're desperate, use this for now:
> 
> `npm i --save react-native-custom-components@https://github.com/facebookarchive/react-native-custom-components.git`
good job,thanks
